CREATE TABLE users (
	date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	email TEXT NOT NULL UNIQUE,
	uid TEXT PRIMARY KEY,
	username TEXT NOT NULL UNIQUE
);

CREATE TABLE blogs (
	context TEXT NOT NULL,
	date_created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	date_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	uid TEXT NOT NULL REFERENCES users ON DELETE CASCADE
);
